edvinnn/Green-Power

TIMEREPORT.md
=> Updated time reporting

TIMEREPORT.md, time_reports/time_report_edvin.md, time_reports/time_report_hampus.md
Created two new time reports, one for each of us, in the appropriate format.
Deleted the old time report.
=> Updated time reports

server/api/routes.js, server/model.js, server/simulator.js
Added overall consumer consumption.
Works as wind consumption.
=> Consumer consumption simulator

server/api/routes.js, server/model.js, server/simulator.js
Consumer consumption: simulates total consumption of consumers.
Prosumer consumption: updates DB with new value of consumption from a specific prosumer id with put API.
=> Consumer model and prosumer consumption put

server/api/routes.js, server/model.js, simulator/api/routes.js, simulator/model.js, simulator/simulator.js
API updated for simulator. Current electricity price is now uploaded to the database and can be fetched with the API (#27).
Introduced more fields to prosumer model for production, buffer and max_buffer. It is now possible to get and update current production, buffer and max buffer from the API. (#28)
=> Updated models for prosumer and simulator

.github/workflows/deploy.yml, .gitmodules, server/server.js, server/website/routes.js, views/dash.ejs, views/index.ejs, views/login.ejs
Added this [submodule](https://github.com/edvinnn/green-power-public) where we can update all public accessible files such ass CSS and JS files that are to be served by the server. 
Those files are for now just a copy of the source files from https://github.com/BlackrockDigital/startbootstrap-sb-admin-2, but it's easier for us to maintain our own repo.
=> Initialize submodule for public files

server/api/routes.js, views/modules/dashboard_main.ejs, views/modules/dashboard_scripts.ejs
Clients can now view their own:
- production
- consumption
- net production
- buffer percentage
- balance
and also view the current electricity price in real time. 
One web socket for each client.
=> Dashboard updates with real time values from web socket

views/modules/dashboard_scripts.ejs
=> Winds chart wrong order bugfix

views/modules/topbar.ejs
=> Mobile view topbar bug-fix

server/api/routes.js, server/website/routes.js, views/modules/dashboard_main.ejs, views/modules/profile_main.ejs, views/modules/topbar.ejs, views/profile.ejs
=> Profile page

server/passport-config.js
=> Iterates trough users with same email

simulator/simulator.js
Solved some bugs in buffer simulator. Buffer SHOULD work as expected now...
=> Simulator fix

views/register.ejs
=> Register page improvements

package.json, server/api/routes.js, server/server.js, server/server_db_utils.js, simulator/simulator.js, views/modules/dashboard_scripts.ejs, yarn.lock
=> Web-socket automatically updates prosumer dashboards

server/passport-config.js, server/website/routes.js
=> Email converted to lowercase

server/api/routes.js, views/modules/manager/dashboard.ejs, views/modules/manager/dashboard_scripts.ejs
Solves #97 
Now quite a lot of logic happens in api routes. Should we include another file in the module that calculates the logic or should it be included in the server_db_utils instead?
=> Production panel of manager dashboard

simulator/simulator.js
Fix bug that makes buffer go under 0 on the occasion that a user has under_production_buy activated, enough balance and very low buffer.
=> Buffer bug

server/api/routes.js, server/model.js, server/server_db_utils.js, server/website/routes.js, simulator/simulator.js, views/modules/manager/dashboard.ejs, views/modules/manager/dashboard_scripts.ejs
Variables to the env file added in order to decice a given production and consumption of the power plant when running, starting and stopped. 
- PLANT_PRODUCTION=1000
- PLANT_CONSUMPTION=300
One more boolean field added to the user database as production_on_off.
HOUSEHOLDS=1000 moved to env file.
Buffer simulator now works for managers aswell. Buffer_max is now set to 1000 for managers and 10 for prosumers on register.
=> Manager Dashboard: Production Panel

.gitignore, package.json, server/api/routes.js, server/model.js, server/server.js, server/server_db_utils.js, server/website/routes.js, views/modules/profile_main.ejs, views/modules/topbar.ejs, yarn.lock
=> Profile picture

server/api/routes.js, server/server_db_utils.js, views/modules/form_checking_scripts.ejs, views/modules/profile_main.ejs, views/profile.ejs, views/register.ejs
=> Change password
